<?php
/**
 * @file
 * Code for the GSB Feature All Research Display feature.
 */

include_once 'gsb_feature_all_research_display.features.inc';


function gsb_feature_all_research_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_state['subtype_name'], array('gsb_all_research_listing-all_research_panel_pane', 'views-exposed-form-gsb-all-research-listing-all-research-panel-pane'))) {
    $view_modes = $form['view_mode']['#options'];
    foreach($view_modes as $key => $value) {
      if($key !== 'compact' AND $key !== 'expanded'){
      unset($form['view_mode']['#options'][$key]);
      }
    }
    $form['view_mode']['#title'] = 'Display Option';
    $form['view_mode']['#weight'] = -99;
    $form['exposed']['filter-field_publication_type_value']['expose_to_visitor']['#weight'] = -98;
    $form['exposed']['filter-field_circle_topics_tid']['expose_to_visitor']['#weight'] = -97;
    $form['exposed']['filter-field_publication_type_value']['expose_to_visitor']['#title'] = 'Publication Type';
    $form['exposed']['filter-field_publication_type_value']['field_publication_type_value']['#weight'] = -87;
    $form['exposed']['filter-field_circle_topics_tid']['expose_to_visitor']['#title'] = 'CIRCLE Topic';
    $form['comments']['#access'] = FALSE;
    $form['links']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_all_research_display_pane_form_validate';

 }

}
function gsb_feature_all_research_display_pane_form_validate(&$form, &$form_state){

  if ($form_state['values']['exposed']['field_centers_research_programs_tid'] == 'All') {
    $form_state['values']['exposed']['filter-field_circle_topics_tid']['expose_to_visitor'] = 0;
  }
}
//function gsb_feature_all_research_display_form

function gsb_feature_all_research_display_form_views_exposed_form_alter(&$form, &$form_state) {

  if ($form['#id'] == 'views-exposed-form-gsb-all-research-listing-all-research-panel-pane') {
    if (isset($form_state['input']['field_centers_research_programs_tid'])) {
      $options = array();
      $filter_on = FALSE;
      $center_id = $form_state['input']['field_centers_research_programs_tid'];
      $center = $form['field_centers_research_programs_tid']['#options'][$center_id];
      foreach ($form['field_circle_topics_tid']['#options'] as $filter_info) {
        foreach ($filter_info->option as $key => $name) {
          if ($filter_on) {
            if (substr($name,0,1) == '-') {
              $filter_info->option[$key] = substr($name,1);
              $options[] = $filter_info;
            }
            else {
              break(2);
            }
          }
          if ($name == $center){
            $filter_on = TRUE;
          }
        }
      }
      $form['field_circle_topics_tid']['#options'] = $options;
    }
  }
}
