<?php
/**
 * @file
 * Code for the GSB Feature All Research Display feature.
 */

include_once 'gsb_feature_all_research_display.features.inc';


function gsb_feature_all_research_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_state['subtype_name'], array('gsb_all_research_listing-all_research_panel_pane'))) {
    $view_modes = $form['view_mode']['#options'];
    foreach ($view_modes as $key => $value) {
      if ($key !== 'compact' AND $key !== 'expanded') {
        unset($form['view_mode']['#options'][$key]);
      }
    }

    $form['view_mode']['#title'] = 'Display Option';
    $form['view_mode']['#weight'] = -99;
    $form['exposed']['filter-field_publication_type_value']['expose_to_visitor']['#weight'] = -98;
    $form['exposed']['filter-field_circle_topics_tid']['expose_to_visitor']['#weight'] = -97;
    $form['exposed']['filter-field_publication_type_value']['expose_to_visitor']['#title'] = '<span class="hide_pub">Publication Type</span>';
    $form['exposed']['filter-field_publication_type_value']['field_publication_type_value']['#weight'] = -87;
    $form['exposed']['filter-field_circle_topics_tid']['expose_to_visitor']['#title'] = '<span class="hide_topic">CIRCLE Topic</span>';
    $form['comments']['#access'] = FALSE;
    $form['links']['#access'] = FALSE;
    $form['exposed']['filter-field_publication_type_value']['field_publication_type_value']['#theme'] = 'select';
    $form['exposed']['filter-field_publication_type_value']['#title'] = t('Allow the user to filter by Publication Type');
    $form['exposed']['filter-field_circle_topics_tid']['field_circle_topics_tid']['#theme'] = 'select';
    $form['exposed']['filter-field_circle_topics_tid']['#title'] = '<span class="topic-label">Allow the user to filter by Research Focus Areas</span>';

    $all_topics = $form['exposed']['filter-field_circle_topics_tid']['field_circle_topics_tid']['#options'];
    $topics = array();
    foreach ($all_topics as $option) {
      foreach ($option->option as $key => $value) {
        $data = array(
          'key' => $key,
          'value' => $value,
        );
        $topics[] = $data;
      }
    }

    drupal_add_js(array('gsb_feature_all_research_display' => array("topics" => $topics)), 'setting');
    drupal_add_js(drupal_get_path('module', 'gsb_feature_all_research_display') . '/js/gsb_feature_all_research_display.js');
    $form['#validate'][] = 'gsb_feature_all_research_display_pane_form_validate';
 }
}
function gsb_feature_all_research_display_pane_form_validate(&$form, &$form_state){
  if ($form_state['values']['exposed']['field_centers_research_programs_tid'] == 'All') {
    $form_state['values']['exposed']['filter-field_circle_topics_tid']['expose_to_visitor'] = 0;
  }
  if ($form_state['values']['exposed']['filter-field_publication_type_value']['expose_to_visitor'] == 1) {
      unset($form_state['values']['exposed']['field_publication_type_value']);
  }
  if($form_state['values']['exposed']['filter-field_circle_topics_tid']['expose_to_visitor'] == 1) {
    unset($form_state['values']['exposed']['field_circle_topics_tid']);
  }
}

//function gsb_feature_all_research_display_form

function gsb_feature_all_research_display_form_views_exposed_form_alter(&$form, &$form_state) {

  if ($form['#id'] == 'views-exposed-form-gsb-all-research-listing-all-research-panel-pane') {
    $form['field_search_field_value']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
    $form['#action'] = '';
    if (isset($form_state['input']['field_centers_research_programs_tid'])) {
      $options = array();
      $filter_on = FALSE;
      $center_id = $form_state['input']['field_centers_research_programs_tid'];
      $center = $form['field_centers_research_programs_tid']['#options'][$center_id];
      foreach ($form['field_circle_topics_tid']['#options'] as $filter_info) {
        foreach ($filter_info->option as $key => $name) {
          if ($filter_on) {
            if (substr($name, 0, 1) == '-') {
              $filter_info->option[$key] = substr($name, 1);
              $options[] = $filter_info;
            }
            else {
              break(2);
            }
          }
          if ($name == $center) {
            $filter_on = TRUE;
          }
        }
      }
      $form['field_circle_topics_tid']['#options'] = $options;
    }
    $display_pub = (!empty($form_state['input']['filter-field_publication_type_value'])) ? $form_state['input']['filter-field_publication_type_value']['expose_to_visitor'] : '';
    $display_topic = (!empty($form_state['input']['filter-field_circle_topics_tid'])) ? $form_state['input']['filter-field_circle_topics_tid']['expose_to_visitor'] : '';

    $fieldset = array();
    $done_button_css = false;
    if ($display_pub || $display_topic) {
      $fieldset = array(
        '#title' => t('Narrow your results'),
        '#type' => 'fieldset',
        '#weight' => 100,
        '#collapsible' => TRUE,
        '#collapsed' => (empty($form_state['input']['field_publication_type_value']) && empty($form_state['input']['field_circle_topics_tid'])) ? TRUE : FALSE,
      );
      $done_button_css = true;
    }

    if ($display_pub) {
      $fieldset['field_publication_type_value'] = $form['field_publication_type_value'];
      $fieldset['field_publication_type_value']['#title'] = t('Publication Type');
      $form['field_publication_type_value'] = FALSE;
      unset($form['#info']['filter-field_publication_type_value']);
    }
    if ($display_topic) {
      if (!empty($options)) {
        $fieldset['field_circle_topics_tid'] = $form['field_circle_topics_tid'];
        $fieldset['field_circle_topics_tid']['#title'] = t('Research Focus Areas');
      }
      $form['field_circle_topics_tid'] = FALSE;
      unset($form['#info']['filter-field_circle_topics_tid']);
    }

    $fieldset['done'] = array(
      '#type' => 'submit',
      '#value' => t('Done'),
      );
    if(!$done_button_css) {
      $fieldset['done']['#attributes'] = array(
      'class' => array(
        'file-icon',
          ),
       );
    }
    
    $fieldset['clear-all'] = array(
      '#type' => 'button',
      '#value' => t('Clear All'),
    );
    $new_form = array();
    foreach ($form as $key => $value) {
      $new_form[$key] = $value;
      if ($key == 'field_tag_tid') {
        $new_form['narrow_search'] = $fieldset;
      }
    }
    $form = $new_form;
    drupal_add_js(drupal_get_path('module', 'gsb_feature_all_research_display') . '/js/gsb_align_exposed_markup.js');
  }
}
